workflows:
  ios-workflow:
    name: iOS Build
    instance_type: mac_mini_m2
    environment:
      vars:
        BUNDLE_ID: "io.qzz.mehrad.spy"
      integrations:
        app_store_connect: Codemagic
    working_directory: ios
    scripts:
      - name: install pods
        script: pod install
      - name: set up code signing
        script: |
          xcode-project use-profiles \
            --type app-store
      - name: build ipa
        script: |
          xcode-project build-ipa \
            --workspace "Spy.xcworkspace" \
            --scheme "Spy" \
            --export-options-plist "$CM_BUILD_DIR/export_options.plist"
    artifacts:
      - build/ios/ipa/*.ipa
